<!--OSCam;1761340993;1.20-unstable_svn;9340;CW_CYCLE_CHECK-->
			<TD CLASS="usercol13"><SPAN>##CWCYCLECHECKED##</SPAN> / <SPAN>##CWCYCLEOK##</SPAN> / <SPAN>##CWCYCLENOK##</SPAN> / <SPAN>##CWCYCLEIGN##</SPAN></TD>
