<!--OSCam;952831796;1.20-unstable_svn;9340;WITH_CARDREADER,MODULE_CCCAM-->
##TPLHEADER##
##TPLMENU##
##TPLMESSAGE##
	<SPAN CLASS="text_entitle">Entitlements for ##READERNAME##</SPAN>
##ENTITLEMENTCONTENT##
##TPLFOOTER##
