<!--OSCam;2517141978;1.20-unstable_svn;9340;WITH_CARDREADER-->
		<TR CLASS="##ENTEXPIERED##"><TD>##ENTTYPE##</TD><TD>##ENTCAID##</TD><TD>##ENTPROVID##</TD><TD>##ENTID##</TD><TD>##ENTCLASS##</TD><TD>##ENTSTARTDATE##</TD><TD>##ENTENDDATE##</TD><TD>##ENTRESNAME##</TD></TR>
