<!--OSCam;171608287;1.20-unstable_svn;8864;-->
	<TABLE border=0 class="configmenu">
		<TR>
			<TD CLASS="##CMENUACTIVE0##"><A HREF="config.html?part=global">Global</A></TD>
##TPLCONFIGMENULB##
			<TD CLASS="##CMENUACTIVE24##"><A HREF="config.html?part=cache">Cache##TPLCMCAPTIONCWC##</A></TD>
##TPLCONFIGMENUCAMD33##
##TPLCONFIGMENUCAMD35##
##TPLCONFIGMENUCAMD35TCP##
##TPLCONFIGMENUNEWCAMD##
##TPLCONFIGMENURADEGAST##
##TPLCONFIGMENUCCCAM##
##TPLCONFIGMENUGBOX##
##TPLCONFIGMENUANTICASC##
##TPLCONFIGMENULCD##
##TPLCONFIGMENUMONITOR##
##TPLCONFIGMENUWEBIF##
##TPLCONFIGMENUSERIAL##
##TPLCONFIGMENUDVBAPI##
		</TR>
	</TABLE>
