<!--OSCam;645652112;1.20-unstable_svn;8864;-->
		<TR CLASS="##ENTEXPIERED##"><TD>##ENTTYPE##</TD><TD>##ENTCAID##</TD><TD>##ENTPROVID##</TD><TD>##ENTID##</TD>		<TD>##ENTCLASS##</TD><TD>##ENTSTARTDATE##</TD><TD>##ENTENDDATE##</TD><TD>##ENTRESNAME##</TD></TR>
