<!--OSCam;1576945758;1.20-unstable_svn;9535;CW_CYCLE_CHECK-->
			<TD CLASS="usercol13" ID="##CWCCYCVIEW##"><SPAN>##CWCYCLECHECKED##</SPAN> / <SPAN>##CWCYCLEOK##</SPAN> / <SPAN>##CWCYCLENOK##</SPAN> / <SPAN>##CWCYCLEIGN##</SPAN></TD>
