<!--OSCam;814073178;1.20-unstable_svn;9705;-->
<DIV ID="subnav">
	<input id="subtoggle" type="checkbox"></input>
	<label class="subtoggle" onclick="" for="subtoggle"></label>
	<UL ID="nav">
			<LI CLASS="##CMENUACTIVE0##"><A HREF="config.html?part=global">Global</A></LI>
##TPLCONFIGMENUANTICASC##
			<LI CLASS="##CMENUACTIVE24##"><A HREF="config.html?part=cache">Cache##TPLCMCAPTIONCWC##</A></LI>
##TPLCONFIGMENULB##
##TPLCONFIGMENUCAMD33##
##TPLCONFIGMENUCAMD35##
##TPLCONFIGMENUCAMD35TCP##
##TPLCONFIGMENUCCCAM##
##TPLCONFIGMENUNEWCAMD##
##TPLCONFIGMENUGBOX##
##TPLCONFIGMENURADEGAST##
##TPLCONFIGMENUSERIAL##
##TPLCONFIGMENUDVBAPI##
##TPLCONFIGMENULCD##
##TPLCONFIGMENUMONITOR##
##TPLCONFIGMENUWEBIF##
	</UL>
</DIV>