<!--OSCam;1384511551;1.20-unstable_svn;9989;-->
<DIV ID="subnav">
	<UL ID="nav">
			<LI CLASS="##CMENUACTIVE0##"><A HREF="config.html?part=global">Global</A></LI>
##TPLCONFIGMENUANTICASC##
			<LI CLASS="##CMENUACTIVE24##"><A HREF="config.html?part=cache">Cache##TPLCMCAPTIONCWC##</A></LI>
##TPLCONFIGMENULB##
##TPLCONFIGMENUCAMD33##
##TPLCONFIGMENUCAMD35##
##TPLCONFIGMENUCAMD35TCP##
##TPLCONFIGMENUCCCAM##
##TPLCONFIGMENUNEWCAMD##
##TPLCONFIGMENUGBOX##
##TPLCONFIGMENURADEGAST##
##TPLCONFIGMENUSCAM##
##TPLCONFIGMENUSERIAL##
##TPLCONFIGMENUDVBAPI##
##TPLCONFIGMENULCD##
##TPLCONFIGMENUMONITOR##
##TPLCONFIGMENUWEBIF##
	</UL>
</DIV>