<!--OSCam;3465697540;1.20-unstable_svn;9705;CW_CYCLE_CHECK-->
			<TD CLASS="usercol13 ##CWCCYCVIEW##"><SPAN>##CWCYCLECHECKED##</SPAN> / <SPAN>##CWCYCLEOK##</SPAN> / <SPAN>##CWCYCLENOK##</SPAN> / <SPAN>##CWCYCLEIGN##</SPAN></TD>
